spring:
  application:
    name: pk-spring-ai-deekseek-r1

server:
  port: ${PORT:8080}

---
spring:
  ai:
    ollama:
      chat:
        base-url: http://localhost:11434/
        options:
          model: deepseek-r1:1.5b